import type {
  Alert,
  ApiLogEntry,
  AuditLog,
  Incident,
  LoginEvent,
  NetworkFlow,
  ResponseActionCatalog,
  ResponseExecution,
} from '../types';

const ago = (ms: number) => new Date(Date.now() - ms).toISOString();
const M = 60 * 1000;
const H = 60 * M;
const D = 24 * H;

// ---------------------------------------------------------------------------
// ALERTS (25+)
// ---------------------------------------------------------------------------
export const mockAlerts: Alert[] = [
  {
    id: 'ALT-001',
    title: 'Phishing Email Detected - Microsoft Credential Harvesting',
    module: 'phishing',
    severity: 'critical',
    riskScore: 92,
    status: 'new',
    summary: 'Sophisticated phishing email impersonating Microsoft security team with credential harvesting URL',
    indicators: [
      { id: 'IND-001', type: 'sender_domain', value: 'micr0soft-verify.xyz', severity: 'critical', description: 'Sender domain uses character substitution to mimic Microsoft' },
      { id: 'IND-002', type: 'urgency_language', value: 'account suspended within 24 hours', severity: 'high', description: 'Message creates artificial urgency to pressure immediate action' },
      { id: 'IND-003', type: 'credential_request', value: 'verify your password', severity: 'critical', description: 'Email requests credential verification through external link' },
      { id: 'IND-004', type: 'suspicious_url', value: 'http://185.220.101.7/login', severity: 'critical', description: 'Embedded URL uses raw IP address instead of legitimate domain' },
    ],
    explanation: 'High Risk: The sender domain micr0soft-verify.xyz closely resembles Microsoft using character substitution (0 for o). The email creates artificial urgency by threatening account suspension within 24 hours. It requests credential verification through an embedded URL that resolves to a raw IP address (185.220.101.7) rather than a legitimate Microsoft domain. These indicators are consistent with a credential harvesting phishing campaign targeting organizational accounts.',
    recommendedActions: [
      { id: 'RA-001', action: 'Quarantine Email', description: 'Remove email from all recipient inboxes', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-002', action: 'Block Sender Domain', description: 'Add micr0soft-verify.xyz to blocklist', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-003', action: 'Block Destination IP', description: 'Block 185.220.101.7 at firewall', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-004', action: 'Notify Targeted Users', description: 'Send security awareness alert', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1566.001', name: 'Spearphishing Attachment', tactic: 'Initial Access' },
      { id: 'T1078', name: 'Valid Accounts', tactic: 'Defense Evasion' },
    ],
    targetUser: 'john.doe@company.com',
    targetService: 'Microsoft 365',
    sourceIp: '185.220.101.7',
    timestamp: ago(15 * M),
  },
  {
    id: 'ALT-002',
    title: 'Impossible Travel Login Detected - john.doe',
    module: 'account_takeover',
    severity: 'critical',
    riskScore: 88,
    status: 'new',
    summary: 'Successful login from Moscow 12 minutes after login from New York indicates credential compromise',
    indicators: [
      { id: 'IND-011', type: 'impossible_travel', value: 'New York, US -> Moscow, RU (12 min)', severity: 'critical', description: 'Geographically impossible movement between logins' },
      { id: 'IND-012', type: 'unknown_device', value: 'Linux-Firefox', severity: 'high', description: 'Device never previously associated with this account' },
      { id: 'IND-013', type: 'failed_then_success', value: '3 failures then success', severity: 'critical', description: 'Successful authentication followed a burst of failures from the same IP' },
    ],
    explanation: 'Critical Risk: User john.doe authenticated from Moscow, Russia only 12 minutes after a successful login from New York, US. Physical travel between these locations is impossible. The session originated from a previously unseen Linux-Firefox device, and the successful login followed three failed attempts from the same IP (185.220.101.7). This pattern is a strong indicator of credential compromise via brute force or stolen credentials.',
    recommendedActions: [
      { id: 'RA-011', action: 'Revoke Active Sessions', description: 'Terminate all sessions for john.doe', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-012', action: 'Force Password Reset', description: 'Require password change and MFA re-enrollment', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-013', action: 'Block Source IP', description: 'Block 185.220.101.7 at identity provider', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
    ],
    mitreTechniques: [
      { id: 'T1078', name: 'Valid Accounts', tactic: 'Defense Evasion' },
      { id: 'T1110.003', name: 'Password Spraying', tactic: 'Credential Access' },
    ],
    targetUser: 'john.doe@company.com',
    targetService: 'Corporate SSO',
    sourceIp: '185.220.101.7',
    timestamp: ago(32 * M),
  },
  {
    id: 'ALT-003',
    title: 'Data Exfiltration Suspected - High Outbound Volume',
    module: 'network',
    severity: 'critical',
    riskScore: 90,
    status: 'new',
    summary: 'Workstation 10.0.4.21 transferred 4.7GB to external host 45.33.32.156 over port 4444',
    indicators: [
      { id: 'IND-021', type: 'high_outbound_volume', value: '4.7 GB to 45.33.32.156', severity: 'critical', description: 'Outbound volume is 40x the user baseline' },
      { id: 'IND-022', type: 'suspicious_port', value: '45.33.32.156:4444', severity: 'critical', description: 'Port 4444 is a default reverse-shell listener port' },
      { id: 'IND-023', type: 'beaconing', value: 'Every 60s +/- 2s', severity: 'high', description: 'Regular beacon interval indicates automated C2 check-ins' },
    ],
    explanation: 'Critical Risk: Internal workstation 10.0.4.21 has transferred 4.7GB of data to external host 45.33.32.156 within one hour. The traffic uses port 4444, a port commonly associated with Meterpreter and reverse-shell payloads, and exhibits beaconing at regular 60-second intervals. The transferred volume is 40 times the weekly baseline for this host. Combined, these indicators strongly suggest active malware command-and-control with staged data exfiltration.',
    recommendedActions: [
      { id: 'RA-021', action: 'Isolate Host 10.0.4.21', description: 'Quarantine the workstation from the network', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-022', action: 'Block C2 IP', description: 'Blackhole 45.33.32.156 at perimeter firewall', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-023', action: 'Capture Forensic Image', description: 'Preserve memory and disk for forensics', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1041', name: 'Exfiltration Over C2 Channel', tactic: 'Exfiltration' },
      { id: 'T1071.001', name: 'Application Layer Protocol: Web Protocols', tactic: 'Command and Control' },
      { id: 'T1572', name: 'Protocol Tunneling', tactic: 'Command and Control' },
    ],
    targetUser: 'svc-backup@company.com',
    targetService: 'File Server',
    sourceIp: '10.0.4.21',
    timestamp: ago(8 * M),
  },
  {
    id: 'ALT-004',
    title: 'Fake CEO Impersonation - Gift Card Fraud Attempt',
    module: 'impersonation',
    severity: 'high',
    riskScore: 82,
    status: 'acknowledged',
    summary: 'Email claiming to be the CEO requests urgent purchase of $1,500 in Amazon gift cards',
    indicators: [
      { id: 'IND-031', type: 'authority_claim', value: 'Chief Executive Officer', severity: 'high', description: 'Sender claims senior executive identity' },
      { id: 'IND-032', type: 'unusual_request', value: 'purchase three Amazon gift cards worth $500', severity: 'critical', description: 'Requests untraceable financial instruments' },
      { id: 'IND-033', type: 'secrecy_request', value: 'Do not inform finance until I return', severity: 'critical', description: 'Demands bypassing normal financial controls' },
      { id: 'IND-034', type: 'urgency_pressure', value: 'within the hour', severity: 'high', description: 'Manufactures time pressure to prevent verification' },
    ],
    explanation: 'High Risk: The message claims to be from the Chief Executive Officer and requests the urgent purchase of three $500 Amazon gift cards for a client settlement. It instructs the recipient not to inform finance and demands action within the hour while claiming unavailability by phone. This is the canonical business email compromise (BEC) gift-card pattern: authority pretext + unusual payment request + secrecy + urgency. The claimed identity could not be verified against any legitimate executive communication channel.',
    recommendedActions: [
      { id: 'RA-031', action: 'Verify Identity Out-of-Band', description: 'Contact the CEO via known phone number', automationLevel: 'manual', requiresApproval: false, priority: 'critical' },
      { id: 'RA-032', action: 'Freeze Pending Financial Requests', description: 'Hold gift card purchases pending verification', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-033', action: 'Notify Finance Department', description: 'Alert finance about the fraud attempt', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1656', name: 'Impersonation', tactic: 'Initial Access' },
      { id: 'T1534', name: 'Internal Spearphishing', tactic: 'Lateral Movement' },
    ],
    targetUser: 'sarah.admin@company.com',
    targetService: 'Email',
    sourceIp: '91.219.237.22',
    timestamp: ago(2 * H),
  },
  {
    id: 'ALT-005',
    title: 'Suspicious URL Clicked - Lookalike Payment Portal',
    module: 'url',
    severity: 'high',
    riskScore: 78,
    status: 'new',
    summary: 'User visited paypa1-secure.top credential page served over HTTP with redirect chain',
    indicators: [
      { id: 'IND-041', type: 'lookalike_domain', value: 'paypa1-secure.top', severity: 'critical', description: 'Domain substitutes 1 for l to mimic PayPal' },
      { id: 'IND-042', type: 'no_tls', value: 'http', severity: 'medium', description: 'Credential page served without TLS encryption' },
      { id: 'IND-043', type: 'redirect_chain', value: '3 hops ending at 185.220.101.44', severity: 'high', description: 'Multi-hop redirect through tracking infrastructure' },
    ],
    explanation: 'High Risk: User alice.wong@company.com clicked a link that resolved to paypa1-secure.top, a character-substitution lookalike of paypal.com. The page was served over unencrypted HTTP and followed a three-hop redirect chain terminating at raw IP 185.220.101.44. The landing page mimics a PayPal login form. It is likely the user\'s entered credentials, if any, have been harvested.',
    recommendedActions: [
      { id: 'RA-041', action: 'Block URL', description: 'Add paypa1-secure.top to web filter', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-042', action: 'Force Password Reset', description: 'Reset credentials for the affected user', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-043', action: 'Warn Users via Proxy Banner', description: 'Enable interstitial warning for similar domains', automationLevel: 'automatic', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1566.002', name: 'Spearphishing Link', tactic: 'Initial Access' },
      { id: 'T1071.001', name: 'Application Layer Protocol: Web Protocols', tactic: 'Command and Control' },
    ],
    targetUser: 'alice.wong@company.com',
    targetService: 'Web Proxy',
    sourceIp: '185.220.101.44',
    timestamp: ago(55 * M),
  },
  {
    id: 'ALT-006',
    title: 'Suspected Voice Deepfake in CFO Wire Transfer Call',
    module: 'deepfake',
    severity: 'critical',
    riskScore: 85,
    status: 'new',
    summary: 'Audio clip of CFO authorizing $250,000 wire transfer shows synthetic voice artifacts',
    indicators: [
      { id: 'IND-051', type: 'synthetic_voice_pattern', value: '92% TTS match', severity: 'critical', description: 'Formant patterns match neural text-to-speech output' },
      { id: 'IND-052', type: 'unnatural_pitch_transition', value: 'Jitter absent', severity: 'high', description: 'Pitch lacks natural human jitter and shimmer' },
      { id: 'IND-053', type: 'background_noise_inconsistency', value: 'Constant noise floor', severity: 'medium', description: 'Background noise does not vary naturally across the clip' },
    ],
    explanation: 'Critical Risk: An audio recording allegedly of the CFO authorizing a $250,000 wire transfer exhibits strong synthetic speech indicators. Formant spacing and micro-prosody match neural text-to-speech output at 92% similarity, natural pitch jitter is absent, and the background noise floor is unnaturally constant. The request originated from an unexpected channel with no prior chain of custody. The clip is assessed as a probable AI-generated voice clone of the CFO.',
    recommendedActions: [
      { id: 'RA-051', action: 'Flag for Manual Verification', description: 'Route to forensic audio analysts', automationLevel: 'manual', requiresApproval: false, priority: 'critical' },
      { id: 'RA-052', action: 'Freeze Pending Financial Requests', description: 'Hold the $250,000 wire transfer', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-053', action: 'Verify Identity Out-of-Band', description: 'Confirm with CFO via known secure channel', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1656', name: 'Impersonation', tactic: 'Initial Access' },
    ],
    targetUser: 'finance-team@company.com',
    targetService: 'Treasury Portal',
    timestamp: ago(4 * H),
  },
  {
    id: 'ALT-007',
    title: 'Password Spraying Campaign Against VPN Portal',
    module: 'account_takeover',
    severity: 'high',
    riskScore: 75,
    status: 'acknowledged',
    summary: 'Single IP attempted logins against 47 accounts within 10 minutes',
    indicators: [
      { id: 'IND-061', type: 'password_spraying', value: '185.220.101.7 -> 47 users', severity: 'critical', description: 'One source targeting many accounts with few attempts each' },
      { id: 'IND-062', type: 'low_and_slow', value: '2 attempts/user', severity: 'medium', description: 'Attempt volume per account kept below lockout thresholds' },
    ],
    explanation: 'High Risk: Source IP 185.220.101.7 attempted authentication against 47 distinct user accounts on the VPN portal within a 10-minute window, keeping attempts per account below lockout thresholds. This low-and-slow pattern is characteristic of password spraying. Two accounts showed successful authentication from this IP shortly after the spraying window and require immediate session revocation.',
    recommendedActions: [
      { id: 'RA-061', action: 'Block Source IP', description: 'Block 185.220.101.7 at the edge', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-062', action: 'Revoke Active Sessions', description: 'Revoke the two affected accounts', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-063', action: 'Enforce MFA', description: 'Require MFA for all VPN logins', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1110.003', name: 'Password Spraying', tactic: 'Credential Access' },
    ],
    targetService: 'VPN Portal',
    sourceIp: '185.220.101.7',
    timestamp: ago(6 * H),
  },
  {
    id: 'ALT-008',
    title: 'API Credential Stuffing Attack on /api/v1/login',
    module: 'api_abuse',
    severity: 'high',
    riskScore: 72,
    status: 'new',
    summary: '412 login requests in 2 minutes from 3 IPs with 89% 401 responses',
    indicators: [
      { id: 'IND-071', type: 'rate_abuse', value: '206 req/min', severity: 'high', description: 'Request rate far exceeds normal client behavior' },
      { id: 'IND-072', type: 'auth_failure_burst', value: '367 x 401', severity: 'critical', description: 'Massive authentication failure count indicates credential stuffing' },
      { id: 'IND-073', type: 'suspicious_user_agent', value: 'python-requests/2.31.0', severity: 'medium', description: 'Scripted client rather than browser or mobile app' },
    ],
    explanation: 'High Risk: The /api/v1/login endpoint received 412 requests within two minutes from three external IPs using python-requests user agents. 367 requests (89%) returned 401 Unauthorized. This is a credential-stuffing campaign testing likely breached username/password pairs. Three accounts returned 200 during the attack window and are considered compromised until verified.',
    recommendedActions: [
      { id: 'RA-071', action: 'Apply Rate Limit', description: 'Throttle to 10 req/min per source IP', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-072', action: 'Block Source IP at WAF', description: 'Deny the three source IPs', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-073', action: 'Revoke API Token', description: 'Invalidate tokens issued during the window', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
    ],
    mitreTechniques: [
      { id: 'T1110.004', name: 'Credential Stuffing', tactic: 'Credential Access' },
      { id: 'T1110', name: 'Brute Force', tactic: 'Credential Access' },
    ],
    targetService: 'Customer API',
    sourceIp: '45.33.49.12',
    timestamp: ago(3 * H),
  },
  {
    id: 'ALT-009',
    title: 'Deepfake Video Call Impersonating IT Director',
    module: 'deepfake',
    severity: 'high',
    riskScore: 76,
    status: 'new',
    summary: 'Live video call participant showed face-blending artifacts inconsistent with authentic video',
    indicators: [
      { id: 'IND-081', type: 'face_blending_artifact', value: 'Temple region', severity: 'high', description: 'Blending boundary visible during head rotation' },
      { id: 'IND-082', type: 'temporal_flickering', value: '12 flicker events', severity: 'medium', description: 'Facial region flickers across consecutive frames' },
      { id: 'IND-083', type: 'lighting_anomaly', value: 'Face vs scene mismatch', severity: 'medium', description: 'Face lighting direction inconsistent with the room' },
    ],
    explanation: 'High Risk: During a video call with an alleged IT Director requesting remote access credentials, the participant\'s video exhibited face-blending artifacts at the temple during head rotation, temporal flickering in the facial region, and lighting inconsistency between the face and the room. The participant declined to perform a head-turn verification test. The video is assessed as a probable real-time deepfake.',
    recommendedActions: [
      { id: 'RA-081', action: 'Flag for Manual Verification', description: 'Escalate recording to deepfake analysts', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
      { id: 'RA-082', action: 'Block Credential Disclosure', description: 'Deny the requested remote access', automationLevel: 'manual', requiresApproval: false, priority: 'critical' },
      { id: 'RA-083', action: 'Verify Identity Out-of-Band', description: 'Call IT Director on known extension', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1656', name: 'Impersonation', tactic: 'Initial Access' },
      { id: 'T1078', name: 'Valid Accounts', tactic: 'Defense Evasion' },
    ],
    targetUser: 'helpdesk@company.com',
    targetService: 'Zoom',
    timestamp: ago(7 * H),
  },
  {
    id: 'ALT-010',
    title: 'Phishing SMS - Bank Account Verification Scam',
    module: 'phishing',
    severity: 'medium',
    riskScore: 58,
    status: 'resolved',
    summary: 'SMS impersonating bank security requests account confirmation via shortlink',
    indicators: [
      { id: 'IND-091', type: 'brand_mismatch', value: 'Chase bank via unknown sender', severity: 'high', description: 'Claims bank identity from unregistered sender' },
      { id: 'IND-092', type: 'suspicious_url', value: 'chase-verify.tk/confirm', severity: 'high', description: 'Shortlink to high-abuse TLD domain' },
      { id: 'IND-093', type: 'urgency_language', value: 'confirm within 12 hours', severity: 'medium', description: 'Deadline pressure typical of smishing' },
    ],
    explanation: 'Medium Risk: An SMS claiming to be from Chase Bank requests account confirmation via a shortlink to chase-verify.tk within 12 hours. The domain uses the .tk high-abuse TLD and the sender is unregistered. Employees who received the SMS were warned and the domain was submitted for blocklisting. No clicks were recorded.',
    recommendedActions: [
      { id: 'RA-091', action: 'Block URL', description: 'Add chase-verify.tk to blocklist', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-092', action: 'Notify Targeted Users', description: 'Warn recipients about the smishing campaign', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1566.002', name: 'Spearphishing Link', tactic: 'Initial Access' },
    ],
    targetUser: 'multiple employees',
    targetService: 'SMS Gateway',
    timestamp: ago(9 * H),
  },
  {
    id: 'ALT-011',
    title: 'DNS Tunneling Detected from Marketing Laptop',
    module: 'network',
    severity: 'high',
    riskScore: 68,
    status: 'new',
    summary: 'Host 10.0.2.88 issued 1,240 NXDOMAIN queries with encoded subdomains',
    indicators: [
      { id: 'IND-101', type: 'dns_tunneling', value: '1,240 queries/hour', severity: 'high', description: 'Query volume and NXDOMAIN ratio far exceed baseline' },
      { id: 'IND-102', type: 'encoded_subdomains', value: 'aGVsbG8ud29ybGQ=.exfil-dns.top', severity: 'high', description: 'Base64-encoded data in subdomain labels' },
    ],
    explanation: 'High Risk: Host 10.0.2.88 issued 1,240 DNS queries in one hour, 91% returning NXDOMAIN, with base64-encoded subdomain labels against exfil-dns.top. This pattern matches DNS tunneling used to covertly exfiltrate data or establish C2 channels. The host has been isolated pending forensic review.',
    recommendedActions: [
      { id: 'RA-101', action: 'Isolate Affected Host', description: 'Quarantine 10.0.2.88 from the network', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'high' },
      { id: 'RA-102', action: 'Block Domain', description: 'Sinkhole exfil-dns.top internally', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1071.004', name: 'DNS', tactic: 'Command and Control' },
      { id: 'T1048.003', name: 'Exfiltration Over Unencrypted Non-C2 Protocol', tactic: 'Exfiltration' },
    ],
    targetUser: 'mike.ross@company.com',
    targetService: 'DNS Resolver',
    sourceIp: '10.0.2.88',
    timestamp: ago(11 * H),
  },
  {
    id: 'ALT-012',
    title: 'Vendor Email Compromise - Invoice Payment Redirect',
    module: 'impersonation',
    severity: 'high',
    riskScore: 70,
    status: 'acknowledged',
    summary: 'Supplier domain typo-squatted in invoice email redirecting payment to attacker account',
    indicators: [
      { id: 'IND-111', type: 'lookalike_domain', value: 'techsupp1y.com vs techsupply.com', severity: 'critical', description: 'Sender domain substitutes 1 for l' },
      { id: 'IND-112', type: 'payment_redirect', value: 'New IBAN DE89 3704...', severity: 'critical', description: 'Updated banking details direct payments to attacker' },
      { id: 'IND-113', type: 'thread_hijack', value: 'Reply in existing thread', severity: 'medium', description: 'Attacker inserted into legitimate invoice thread' },
    ],
    explanation: 'High Risk: An attacker registered techsupp1y.com (typo-squat of techsupply.com) and hijacked an existing invoice thread, requesting payment redirection to a new German IBAN. The reply-to address differs from the visible sender. The accounting department flagged the change as unusual before any payment was issued. The legitimate vendor confirmed the request was fraudulent.',
    recommendedActions: [
      { id: 'RA-111', action: 'Freeze Pending Financial Requests', description: 'Cancel the redirected payment', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-112', action: 'Block Sender Domain', description: 'Block techsupp1y.com at mail gateway', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-113', action: 'Report Impersonation', description: 'File report with bank and IC3', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1656', name: 'Impersonation', tactic: 'Initial Access' },
      { id: 'T1585.002', name: 'Establish Accounts: Email Accounts', tactic: 'Resource Development' },
    ],
    targetUser: 'accounting@company.com',
    targetService: 'Email',
    timestamp: ago(13 * H),
  },
  {
    id: 'ALT-013',
    title: 'Suspicious Admin Session - Off-Hours Privilege Escalation',
    module: 'account_takeover',
    severity: 'high',
    riskScore: 74,
    status: 'new',
    summary: 'Service account granted admin rights at 03:14 UTC from unrecognized IP',
    indicators: [
      { id: 'IND-121', type: 'unusual_hour', value: '03:14 UTC', severity: 'medium', description: 'Administrative activity far outside business hours' },
      { id: 'IND-122', type: 'privilege_escalation', value: 'user -> domain admin', severity: 'critical', description: 'Massive privilege elevation on service account' },
      { id: 'IND-123', type: 'new_source_ip', value: '45.33.22.10', severity: 'high', description: 'Admin session from previously unseen IP' },
    ],
    explanation: 'High Risk: The svc-reports service account was granted domain admin privileges at 03:14 UTC from IP 45.33.22.10, an address with no prior association to the organization. The account had not been used for 63 days prior. Service accounts should never receive interactive admin grants; this indicates stolen credentials and lateral movement preparation.',
    recommendedActions: [
      { id: 'RA-121', action: 'Revoke Active Sessions', description: 'Kill the elevated session immediately', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-122', action: 'Revert Privilege Change', description: 'Remove domain admin from svc-reports', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-123', action: 'Block Source IP', description: 'Block 45.33.22.10 at perimeter', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1078.002', name: 'Domain Accounts', tactic: 'Defense Evasion' },
      { id: 'T1098', name: 'Account Manipulation', tactic: 'Persistence' },
    ],
    targetUser: 'svc-reports',
    targetService: 'Active Directory',
    sourceIp: '45.33.22.10',
    timestamp: ago(14 * H),
  },
  {
    id: 'ALT-014',
    title: 'Malicious Document Attachment - Macro Downloader',
    module: 'phishing',
    severity: 'high',
    riskScore: 73,
    status: 'resolved',
    summary: 'Invoice-themed attachment contains VBA macro downloading payload from 45.33.19.79',
    indicators: [
      { id: 'IND-131', type: 'suspicious_attachment', value: 'Invoice_Q3.docm', severity: 'high', description: 'Macro-enabled document with invoice lure theme' },
      { id: 'IND-132', type: 'macro_download', value: 'http://45.33.19.79/payload.bin', severity: 'critical', description: 'VBA AutoOpen downloads executable from raw IP' },
      { id: 'IND-133', type: 'brand_mismatch', value: 'DHL branding, unrelated sender', severity: 'medium', description: 'Shipment lure from non-logistics domain' },
    ],
    explanation: 'High Risk: An invoice-themed macro-enabled document (Invoice_Q3.docm) impersonating DHL contains a VBA AutoOpen routine that downloads payload.bin from raw IP 45.33.19.79. The sender domain has no relationship with DHL. The attachment was quarantined before any user execution. Sandbox detonation confirmed the download attempt.',
    recommendedActions: [
      { id: 'RA-131', action: 'Quarantine Email', description: 'Remove message from all inboxes', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-132', action: 'Block Destination IP', description: 'Block 45.33.19.79 at firewall', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-133', action: 'Notify Targeted Users', description: 'Warn the finance team about the lure', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1566.001', name: 'Spearphishing Attachment', tactic: 'Initial Access' },
      { id: 'T1204.002', name: 'User Execution: Malicious File', tactic: 'Execution' },
    ],
    targetUser: 'finance@company.com',
    targetService: 'Exchange Online',
    sourceIp: '45.33.19.79',
    timestamp: ago(16 * H),
  },
  {
    id: 'ALT-015',
    title: 'API Enumeration Attack on /api/v1/users',
    module: 'api_abuse',
    severity: 'medium',
    riskScore: 52,
    status: 'dismissed',
    summary: 'Sequential ID enumeration across user records from single token',
    indicators: [
      { id: 'IND-141', type: 'bulk_data_access', value: '/api/v1/users/{id} x3,410', severity: 'high', description: 'Sequential ID access pattern across user records' },
      { id: 'IND-142', type: 'rate_abuse', value: '58 req/min sustained', severity: 'medium', description: 'Sustained access above the 30 req/min normal band' },
    ],
    explanation: 'Medium Risk: A single API token accessed 3,410 user records in sequential ID order over 58 minutes. The pattern is consistent with enumeration using an IDOR-style vulnerability. Investigation revealed the access came from an authorized data warehouse sync job with an outdated configuration; the finding was downgraded and the job was patched to use batch endpoints.',
    recommendedActions: [
      { id: 'RA-141', action: 'Apply Rate Limit', description: 'Enforce per-token rate limits', automationLevel: 'automatic', requiresApproval: false, priority: 'medium' },
      { id: 'RA-142', action: 'Audit Endpoint Authorization', description: 'Review object-level permissions', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1213', name: 'Data from Information Repositories', tactic: 'Collection' },
    ],
    targetService: 'Customer API',
    timestamp: ago(20 * H),
  },
  {
    id: 'ALT-016',
    title: 'C2 Beaconing to Tor Exit Node from Dev Server',
    module: 'network',
    severity: 'critical',
    riskScore: 87,
    status: 'new',
    summary: 'dev-ci-02 established repeated TLS connections to 185.220.101.45 port 9001',
    indicators: [
      { id: 'IND-151', type: 'known_bad_range', value: '185.220.101.45', severity: 'critical', description: 'Destination is a Tor exit node, common for anonymized C2' },
      { id: 'IND-152', type: 'beaconing_pattern', value: 'Every 120s', severity: 'high', description: 'Fixed-interval TLS connections over 6 hours' },
      { id: 'IND-153', type: 'unusual_process', value: 'powershell.exe on Linux host', severity: 'high', description: 'Unexpected process initiating outbound C2' },
    ],
    explanation: 'Critical Risk: dev-ci-02 has established TLS connections every 120 seconds for six hours to 185.220.101.45:9001, a Tor exit node. The initiating process is powershell.exe running under WINE on the Linux CI server, indicating a compromised build dependency attempting anonymized C2. The server builds production artifacts and must be treated as fully compromised.',
    recommendedActions: [
      { id: 'RA-151', action: 'Isolate Affected Host', description: 'Remove dev-ci-02 from the network', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-152', action: 'Block C2 Destination', description: 'Drop traffic to 185.220.101.0/24', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-153', action: 'Rebuild CI Pipeline', description: 'Rotate all build secrets and rebuild from clean images', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1090.003', name: 'Proxy: Multi-hop Proxy', tactic: 'Command and Control' },
      { id: 'T1071.001', name: 'Application Layer Protocol: Web Protocols', tactic: 'Command and Control' },
    ],
    targetUser: 'svc-ci',
    targetService: 'CI/CD Pipeline',
    sourceIp: '10.0.7.2',
    timestamp: ago(22 * H),
  },
  {
    id: 'ALT-017',
    title: 'Lookalike Domain Registered - company-secure.net',
    module: 'url',
    severity: 'medium',
    riskScore: 55,
    status: 'acknowledged',
    summary: 'Freshly registered typosquat domain mimicking corporate SSO portal',
    indicators: [
      { id: 'IND-161', type: 'lookalike_domain', value: 'company-secure.net', severity: 'high', description: 'Domain mimics the corporate SSO naming pattern' },
      { id: 'IND-162', type: 'recent_registration', value: 'Registered 3 days ago', severity: 'medium', description: 'Age is consistent with campaign infrastructure' },
      { id: 'IND-163', type: 'fake_login_page', value: 'SSO clone detected', severity: 'high', description: 'Parked host serves a clone of the corporate login page' },
    ],
    explanation: 'Medium Risk: The domain company-secure.net was registered three days ago and now serves a pixel-accurate clone of the corporate SSO login page. No phishing emails referencing it have been observed yet, suggesting infrastructure preparation for an upcoming campaign. Preemptive blocklisting and brand protection takedown have been initiated.',
    recommendedActions: [
      { id: 'RA-161', action: 'Block URL', description: 'Blocklist company-secure.net preemptively', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-162', action: 'Submit Takedown Request', description: 'File abuse report with registrar', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1584.006', name: 'Compromise Infrastructure: Web Services', tactic: 'Resource Development' },
    ],
    targetService: 'Corporate SSO',
    timestamp: ago(26 * H),
  },
  {
    id: 'ALT-018',
    title: 'Insider Threat - Bulk CRM Export Before Resignation',
    module: 'network',
    severity: 'high',
    riskScore: 66,
    status: 'acknowledged',
    summary: 'Sales user exported 18,400 customer records two weeks after resignation notice',
    indicators: [
      { id: 'IND-171', type: 'bulk_data_access', value: '18,400 records exported', severity: 'high', description: 'Export volume is 95th percentile for the role' },
      { id: 'IND-172', type: 'off_hours_activity', value: '22:41 local', severity: 'medium', description: 'Activity outside normal working pattern' },
      { id: 'IND-173', type: 'usb_transfer', value: '2.1GB to USB device', severity: 'high', description: 'Large removable-media write shortly after export' },
    ],
    explanation: 'High Risk: A sales employee gave notice 16 days ago and has since exported 18,400 CRM customer records (95th percentile for the role) at 22:41 local time, followed by a 2.1GB write to a removable USB device. The pattern matches pre-departure data theft. Legal and HR have been engaged, and DLP monitoring on the account has been raised to strict.',
    recommendedActions: [
      { id: 'RA-171', action: 'Revoke Data Export Rights', description: 'Disable bulk export for the account', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'high' },
      { id: 'RA-172', action: 'Preserve Audit Evidence', description: 'Snapshot CRM and USB logs for legal', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
      { id: 'RA-173', action: 'Notify HR and Legal', description: 'Coordinate response with HR counsel', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1052.001', name: 'Exfiltration over USB', tactic: 'Exfiltration' },
      { id: 'T1213', name: 'Data from Information Repositories', tactic: 'Collection' },
    ],
    targetUser: 'david.kim@company.com',
    targetService: 'CRM',
    sourceIp: '10.0.3.14',
    timestamp: ago(30 * H),
  },
  {
    id: 'ALT-019',
    title: 'Phishing Email - Internal HR Portal Credential Lure',
    module: 'phishing',
    severity: 'high',
    riskScore: 69,
    status: 'new',
    summary: 'Fake HR portal email targets payroll details with urgency framing',
    indicators: [
      { id: 'IND-181', type: 'sender_domain', value: 'hr-portal-update.top', severity: 'high', description: 'Sender domain mimics internal HR portal naming' },
      { id: 'IND-182', type: 'credential_request', value: 'confirm payroll account', severity: 'critical', description: 'Requests payroll credential entry on external site' },
      { id: 'IND-183', type: 'urgency_language', value: 'deadline today 5 PM', severity: 'high', description: 'Same-day deadline pressures hasty action' },
    ],
    explanation: 'High Risk: An email from hr-portal-update.top claims payroll details will be forfeited unless the recipient confirms their account on an external portal before 5 PM today. The domain is 4 days old and hosted on shared phishing infrastructure. 34 employees received the message; two clicked the link but entered no credentials. Both have been advised to report any anomalies.',
    recommendedActions: [
      { id: 'RA-181', action: 'Quarantine Email', description: 'Purge from all 34 inboxes', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-182', action: 'Block Sender Domain', description: 'Block hr-portal-update.top', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-183', action: 'Notify Targeted Users', description: 'Confirm no credentials were entered', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1566.002', name: 'Spearphishing Link', tactic: 'Initial Access' },
    ],
    targetUser: 'all-staff@company.com',
    targetService: 'Email',
    timestamp: ago(34 * H),
  },
  {
    id: 'ALT-020',
    title: 'Suspected Deepfake Image in Executive Press Release',
    module: 'deepfake',
    severity: 'medium',
    riskScore: 49,
    status: 'new',
    summary: 'Press-release photo of CEO shows facial boundary and metadata inconsistencies',
    indicators: [
      { id: 'IND-191', type: 'facial_boundary_inconsistency', value: 'Jawline region', severity: 'medium', description: 'Blending artifacts around jaw boundary' },
      { id: 'IND-192', type: 'metadata_inconsistency', value: 'GIMP edit trace', severity: 'medium', description: 'Editor metadata inconsistent with camera capture' },
    ],
    explanation: 'Medium Risk: A press-release photograph of the CEO shows facial boundary blending artifacts along the jawline and GIMP editing metadata inconsistent with the claimed camera capture. The manipulation is moderate and may be benign retouching, but the image was distributed to media outlets and must be verified against the original before further publication.',
    recommendedActions: [
      { id: 'RA-191', action: 'Flag for Manual Verification', description: 'Route to media forensics for expert review', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
      { id: 'RA-192', action: 'Preserve Original Evidence', description: 'Hash and archive the file', automationLevel: 'automatic', requiresApproval: false, priority: 'low' },
    ],
    mitreTechniques: [
      { id: 'T1656', name: 'Impersonation', tactic: 'Initial Access' },
    ],
    targetUser: 'comms@company.com',
    targetService: 'Press Portal',
    timestamp: ago(38 * H),
  },
  {
    id: 'ALT-021',
    title: 'Repeated MFA Fatigue Push Bombing',
    module: 'account_takeover',
    severity: 'medium',
    riskScore: 57,
    status: 'resolved',
    summary: 'Attacker with valid password sent 28 MFA push requests to fatigue the user',
    indicators: [
      { id: 'IND-201', type: 'mfa_fatigue', value: '28 push requests in 9 min', severity: 'high', description: 'Push bombing indicates valid primary credentials' },
      { id: 'IND-202', type: 'valid_password_unknown_context', value: 'Correct password, wrong IP', severity: 'critical', description: 'Password correctness implies prior credential theft' },
    ],
    explanation: 'Medium Risk: An attacker authenticated with the correct password for emma.davis@company.com and issued 28 MFA push notifications in nine minutes attempting fatigue-based approval. The user did not approve and reported the storm. The valid password confirms prior credential theft; the password was reset and number-matching MFA was enforced.',
    recommendedActions: [
      { id: 'RA-201', action: 'Force Password Reset', description: 'Reset compromised password', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-202', action: 'Require Additional Authentication', description: 'Enable number-matching MFA', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1621', name: 'Multi-Factor Authentication Request Generation', tactic: 'Credential Access' },
      { id: 'T1078', name: 'Valid Accounts', tactic: 'Defense Evasion' },
    ],
    targetUser: 'emma.davis@company.com',
    targetService: 'Corporate SSO',
    sourceIp: '91.219.238.100',
    timestamp: ago(44 * H),
  },
  {
    id: 'ALT-022',
    title: 'Port Scan Followed by SSH Brute Force on Jump Host',
    module: 'network',
    severity: 'medium',
    riskScore: 54,
    status: 'resolved',
    summary: 'External host scanned the DMZ then attacked SSH on the jump host',
    indicators: [
      { id: 'IND-211', type: 'port_scan', value: '1,024 ports in 40s', severity: 'medium', description: 'Rapid full-port scan is classic reconnaissance' },
      { id: 'IND-212', type: 'ssh_brute_force', value: '312 failed SSH auths', severity: 'high', description: 'Sustained brute force against sshd' },
    ],
    explanation: 'Medium Risk: External host 45.33.31.88 performed a full TCP port scan of the DMZ (1,024 ports in 40 seconds) and then launched an SSH brute-force attack (312 failed authentications) against the jump host. No successful authentications occurred. The IP was blocked and fail2ban thresholds were tightened across the fleet.',
    recommendedActions: [
      { id: 'RA-211', action: 'Block Source IP', description: 'Block 45.33.31.88 at perimeter', automationLevel: 'automatic', requiresApproval: false, priority: 'high' },
      { id: 'RA-212', action: 'Harden SSH', description: 'Enforce key-only auth and rate limiting', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1046', name: 'Network Service Scanning', tactic: 'Discovery' },
      { id: 'T1110', name: 'Brute Force', tactic: 'Credential Access' },
    ],
    targetService: 'SSH Jump Host',
    sourceIp: '45.33.31.88',
    timestamp: ago(50 * H),
  },
  {
    id: 'ALT-023',
    title: 'Impersonation via WhatsApp - Fake CFO Voice Note',
    module: 'impersonation',
    severity: 'medium',
    riskScore: 61,
    status: 'new',
    summary: 'Voice note on WhatsApp claims CFO needs urgent vendor payment details',
    indicators: [
      { id: 'IND-221', type: 'new_channel_for_identity', value: 'WhatsApp from unknown number', severity: 'high', description: 'CFO does not use WhatsApp for business' },
      { id: 'IND-222', type: 'urgency_pressure', value: 'before the board call', severity: 'medium', description: 'Time-boxed to prevent verification' },
      { id: 'IND-223', type: 'sensitive_data_request', value: 'Vendor banking details', severity: 'high', description: 'Requests sensitive financial data' },
    ],
    explanation: 'Medium Risk: A WhatsApp voice note from an unknown number, claiming to be the CFO, requests vendor banking details ahead of a board call. The CFO does not use WhatsApp for business communication, and the voice shows mild synthetic characteristics. The recipient did not respond and reported the message. Monitoring has been extended to messaging channels.',
    recommendedActions: [
      { id: 'RA-221', action: 'Verify Identity Out-of-Band', description: 'Confirm with CFO via known channel', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
      { id: 'RA-222', action: 'Notify Finance Department', description: 'Warn about messaging-channel fraud', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1656', name: 'Impersonation', tactic: 'Initial Access' },
    ],
    targetUser: 'laura.perez@company.com',
    targetService: 'WhatsApp Business',
    timestamp: ago(56 * H),
  },
  {
    id: 'ALT-024',
    title: 'Malicious Redirect on Marketing Subdomain',
    module: 'url',
    severity: 'medium',
    riskScore: 47,
    status: 'resolved',
    summary: 'Compromised campaign subdomain redirects visitors to scam casino site',
    indicators: [
      { id: 'IND-231', type: 'malicious_redirect', value: 'promo.company.com -> casino-scam.top', severity: 'high', description: 'Server-side redirect to scam destination' },
      { id: 'IND-232', type: 'suspicious_tld', value: '.top', severity: 'medium', description: 'Destination uses a high-abuse TLD' },
    ],
    explanation: 'Medium Risk: The marketing subdomain promo.company.com, running an outdated CMS plugin, was compromised to server-side redirect approximately 8% of visitors to casino-scam.top. The plugin was patched, the redirect removed, and the destination blocklisted. Web server logs indicate roughly 410 users were affected before remediation.',
    recommendedActions: [
      { id: 'RA-231', action: 'Patch Compromised Component', description: 'Update the CMS plugin and review access logs', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
      { id: 'RA-232', action: 'Block URL', description: 'Blocklist casino-scam.top', automationLevel: 'automatic', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1190', name: 'Exploit Public-Facing Application', tactic: 'Initial Access' },
      { id: 'T1071.001', name: 'Application Layer Protocol: Web Protocols', tactic: 'Command and Control' },
    ],
    targetService: 'Marketing CMS',
    timestamp: ago(62 * H),
  },
  {
    id: 'ALT-025',
    title: 'Successful Login After Brute Force - jane.smith',
    module: 'account_takeover',
    severity: 'critical',
    riskScore: 83,
    status: 'acknowledged',
    summary: '5 failed attempts from 91.219.237.22 followed by successful login and mailbox rule creation',
    indicators: [
      { id: 'IND-241', type: 'success_after_failures', value: '5 failures -> success', severity: 'critical', description: 'Successful auth after repeated failures from same IP' },
      { id: 'IND-242', type: 'mailbox_rule_creation', value: 'Forward to exfil@mail.com', severity: 'critical', description: 'Attacker created auto-forward for mail exfiltration' },
    ],
    explanation: 'Critical Risk: Five failed logins for jane.smith from 91.219.237.22 were followed by a successful authentication 40 seconds later. Within four minutes, the attacker created a hidden inbox rule forwarding all finance-related mail to exfil@mail.com. The account is confirmed compromised. Sessions were revoked and the forwarding rule removed.',
    recommendedActions: [
      { id: 'RA-241', action: 'Revoke Active Sessions', description: 'Terminate all sessions for jane.smith', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
      { id: 'RA-242', action: 'Force Password Reset', description: 'Reset password and re-enroll MFA', automationLevel: 'automatic', requiresApproval: false, priority: 'critical' },
      { id: 'RA-243', action: 'Remove Malicious Rules', description: 'Delete the auto-forward rule and audit all rules', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'critical' },
    ],
    mitreTechniques: [
      { id: 'T1110', name: 'Brute Force', tactic: 'Credential Access' },
      { id: 'T1114.003', name: 'Email Collection: Email Forwarding Rule', tactic: 'Collection' },
    ],
    targetUser: 'jane.smith@company.com',
    targetService: 'Microsoft 365',
    sourceIp: '91.219.237.22',
    timestamp: ago(68 * H),
  },
  {
    id: 'ALT-026',
    title: 'Anomalous Cloud Storage Download Burst',
    module: 'api_abuse',
    severity: 'medium',
    riskScore: 51,
    status: 'new',
    summary: 'Service token downloaded 340 objects from restricted bucket in 12 minutes',
    indicators: [
      { id: 'IND-251', type: 'bulk_data_access', value: '340 objects / 12 min', severity: 'high', description: 'Download burst 60x the token baseline' },
      { id: 'IND-252', type: 'unusual_endpoint_access', value: 'First access to restricted/ prefix', severity: 'medium', description: 'Token had never touched the restricted prefix before' },
    ],
    explanation: 'Medium Risk: A reporting service token downloaded 340 objects from the restricted/ prefix of the data-lake bucket in 12 minutes, 60 times its baseline and its first-ever access to that prefix. The token\'s scope may be broader than required. The token was rotated and the restricted prefix is being moved to a separate scoped credential.',
    recommendedActions: [
      { id: 'RA-251', action: 'Revoke API Token', description: 'Rotate the service token', automationLevel: 'semi-automatic', requiresApproval: true, priority: 'high' },
      { id: 'RA-252', action: 'Audit Endpoint Authorization', description: 'Apply least privilege to bucket scopes', automationLevel: 'manual', requiresApproval: false, priority: 'medium' },
    ],
    mitreTechniques: [
      { id: 'T1530', name: 'Data from Cloud Storage', tactic: 'Collection' },
    ],
    targetService: 'Cloud Data Lake',
    timestamp: ago(72 * H),
  },
  {
    id: 'ALT-027',
    title: 'Deepfake Audio in Voicemail Targeting CFO',
    module: 'deepfake',
    severity: 'medium',
    riskScore: 58,
    status: 'new',
    summary: 'Voicemail allegedly from bank relationship manager requests payment confirmation',
    indicators: [
      { id: 'IND-261', type: 'synthetic_voice_pattern', value: '81% TTS match', severity: 'high', description: 'Voice exhibits neural synthesis characteristics' },
      { id: 'IND-262', type: 'spectral_anomaly', value: 'Hard rolloff at 14kHz', severity: 'medium', description: 'Spectrum shows synthesis-typical cutoff' },
    ],
    explanation: 'Medium Risk: A voicemail allegedly from the company\'s bank relationship manager requests confirmation of a pending payment. Spectral analysis shows an 81% match to neural TTS output and a hard spectral rolloff at 14kHz typical of synthetic speech. The bank confirmed no such call was placed. Finance teams have been briefed.',
    recommendedActions: [
      { id: 'RA-261', action: 'Flag for Manual Verification', description: 'Route to audio forensics', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
      { id: 'RA-262', action: 'Verify Identity Out-of-Band', description: 'Confirm with bank via official line', automationLevel: 'manual', requiresApproval: false, priority: 'high' },
    ],
    mitreTechniques: [
      { id: 'T1656', name: 'Impersonation', tactic: 'Initial Access' },
    ],
    targetUser: 'cfo-office@company.com',
    targetService: 'Voicemail',
    timestamp: ago(80 * H),
  },
];

// ---------------------------------------------------------------------------
// INCIDENTS (8)
// ---------------------------------------------------------------------------
export const mockIncidents: Incident[] = [
  {
    id: 'INC-001',
    title: 'Microsoft Credential Phishing Campaign',
    severity: 'critical',
    status: 'investigating',
    assignedTo: 'Alice Chen',
    linkedAlertIds: ['ALT-001', 'ALT-019'],
    timeline: [
      { id: 'EV-001', action: 'Incident Created', actor: 'Alice Chen', timestamp: ago(14 * M), details: 'Incident opened after ALT-001 detection of credential harvesting campaign' },
      { id: 'EV-002', action: 'Status Changed', actor: 'Alice Chen', timestamp: ago(10 * M), details: 'Status changed from Open to Investigating' },
      { id: 'EV-003', action: 'Response Executed', actor: 'System (Simulated)', timestamp: ago(9 * M), details: 'Quarantine Email executed automatically for 34 inboxes' },
    ],
    createdAt: ago(14 * M),
    updatedAt: ago(9 * M),
  },
  {
    id: 'INC-002',
    title: 'john.doe Account Compromise - Impossible Travel',
    severity: 'critical',
    status: 'open',
    assignedTo: 'Bob Kumar',
    linkedAlertIds: ['ALT-002', 'ALT-007'],
    timeline: [
      { id: 'EV-011', action: 'Incident Created', actor: 'Bob Kumar', timestamp: ago(30 * M), details: 'Impossible travel and brute force evidence correlated into one incident' },
    ],
    createdAt: ago(30 * M),
    updatedAt: ago(30 * M),
  },
  {
    id: 'INC-003',
    title: 'Data Exfiltration from 10.0.4.21 via C2',
    severity: 'critical',
    status: 'contained',
    assignedTo: 'Carlos Reyes',
    linkedAlertIds: ['ALT-003', 'ALT-016'],
    timeline: [
      { id: 'EV-021', action: 'Incident Created', actor: 'Carlos Reyes', timestamp: ago(7 * H), details: 'Exfiltration and C2 beaconing correlated to single compromised host' },
      { id: 'EV-022', action: 'Host Isolated', actor: 'System (Simulated)', timestamp: ago(6 * H), details: 'Isolate Host 10.0.4.21 executed with approval from Carlos Reyes' },
      { id: 'EV-023', action: 'Status Changed', actor: 'Carlos Reyes', timestamp: ago(5 * H), details: 'Status changed from Investigating to Contained after firewall blackhole of 45.33.32.156' },
    ],
    createdAt: ago(7 * H),
    updatedAt: ago(5 * H),
  },
  {
    id: 'INC-004',
    title: 'CEO Gift Card BEC Attempt',
    severity: 'high',
    status: 'closed',
    assignedTo: 'Alice Chen',
    linkedAlertIds: ['ALT-004', 'ALT-023'],
    timeline: [
      { id: 'EV-031', action: 'Incident Created', actor: 'Alice Chen', timestamp: ago(2 * D), details: 'BEC pattern detected across email and WhatsApp channels' },
      { id: 'EV-032', action: 'Identity Verified', actor: 'Bob Kumar', timestamp: ago(2 * D - 30 * M), details: 'CEO confirmed no such request via verified phone call' },
      { id: 'EV-033', action: 'Status Changed', actor: 'Alice Chen', timestamp: ago(40 * H), details: 'Status changed to Closed: payments frozen, staff briefed, no loss incurred' },
    ],
    createdAt: ago(46 * H),
    updatedAt: ago(40 * H),
  },
  {
    id: 'INC-005',
    title: 'PayPal Lookalike Credential Harvesting',
    severity: 'high',
    status: 'investigating',
    assignedTo: 'Bob Kumar',
    linkedAlertIds: ['ALT-005', 'ALT-017'],
    timeline: [
      { id: 'EV-041', action: 'Incident Created', actor: 'Bob Kumar', timestamp: ago(54 * H), details: 'Clicked lookalike link correlated with pre-campaign domain registration' },
      { id: 'EV-042', action: 'Credentials Reset', actor: 'System (Simulated)', timestamp: ago(53 * H), details: 'Force Password Reset executed for alice.wong@company.com' },
    ],
    createdAt: ago(54 * H),
    updatedAt: ago(53 * H),
  },
  {
    id: 'INC-006',
    title: 'CFO Voice Clone Wire Fraud Attempt',
    severity: 'critical',
    status: 'open',
    linkedAlertIds: ['ALT-006', 'ALT-027'],
    timeline: [
      { id: 'EV-051', action: 'Incident Created', actor: 'SOC Automation', timestamp: ago(4 * H), details: 'Deepfake audio alerts correlated into wire-fraud incident' },
    ],
    createdAt: ago(4 * H),
    updatedAt: ago(4 * H),
  },
  {
    id: 'INC-007',
    title: 'Insider Data Theft - Departing Sales Employee',
    severity: 'high',
    status: 'investigating',
    assignedTo: 'Carlos Reyes',
    linkedAlertIds: ['ALT-018'],
    timeline: [
      { id: 'EV-061', action: 'Incident Created', actor: 'Carlos Reyes', timestamp: ago(28 * H), details: 'CRM export and USB transfer flagged as pre-departure theft' },
      { id: 'EV-062', action: 'Legal Engaged', actor: 'Alice Chen', timestamp: ago(26 * H), details: 'HR and legal counsel joined the response' },
      { id: 'EV-063', action: 'Export Rights Revoked', actor: 'System (Simulated)', timestamp: ago(25 * H), details: 'Revoke Data Export Rights executed with approval' },
    ],
    createdAt: ago(28 * H),
    updatedAt: ago(25 * H),
  },
  {
    id: 'INC-008',
    title: 'jane.smith Mailbox Compromise and Exfil Rule',
    severity: 'critical',
    status: 'contained',
    assignedTo: 'Alice Chen',
    linkedAlertIds: ['ALT-025', 'ALT-021'],
    timeline: [
      { id: 'EV-071', action: 'Incident Created', actor: 'Alice Chen', timestamp: ago(66 * H), details: 'Brute-force compromise with forwarding rule created' },
      { id: 'EV-072', action: 'Sessions Revoked', actor: 'System (Simulated)', timestamp: ago(65 * H), details: 'All sessions for jane.smith revoked with approval' },
      { id: 'EV-073', action: 'Malicious Rule Removed', actor: 'System (Simulated)', timestamp: ago(64 * H), details: 'Auto-forward to exfil@mail.com removed; all rules audited' },
      { id: 'EV-074', action: 'Status Changed', actor: 'Alice Chen', timestamp: ago(60 * H), details: 'Status changed to Contained; monitoring retained' },
    ],
    createdAt: ago(66 * H),
    updatedAt: ago(60 * H),
  },
];

// ---------------------------------------------------------------------------
// LOGIN EVENTS (30+)
// ---------------------------------------------------------------------------
export const mockLoginEvents: LoginEvent[] = [
  { id: 'LE-001', userId: 'USR-101', username: 'john.doe', sourceIp: '10.0.1.45', location: 'New York, US', device: 'Windows-Chrome', status: 'success', riskScore: 5, timestamp: ago(70 * H), anomalies: [] },
  { id: 'LE-002', userId: 'USR-101', username: 'john.doe', sourceIp: '185.220.101.7', location: 'Moscow, RU', device: 'Linux-Firefox', status: 'failed', riskScore: 70, timestamp: ago(69.9 * H), anomalies: ['Unknown device', 'Foreign country'] },
  { id: 'LE-003', userId: 'USR-101', username: 'john.doe', sourceIp: '185.220.101.7', location: 'Moscow, RU', device: 'Linux-Firefox', status: 'failed', riskScore: 72, timestamp: ago(69.85 * H), anomalies: ['Unknown device', 'Foreign country'] },
  { id: 'LE-004', userId: 'USR-101', username: 'john.doe', sourceIp: '185.220.101.7', location: 'Moscow, RU', device: 'Linux-Firefox', status: 'success', riskScore: 92, timestamp: ago(69.8 * H), anomalies: ['Impossible travel', 'Success after failures', 'Unknown device'] },
  { id: 'LE-005', userId: 'USR-102', username: 'jane.smith', sourceIp: '10.0.1.50', location: 'New York, US', device: 'MacOS-Safari', status: 'success', riskScore: 4, timestamp: ago(69 * H), anomalies: [] },
  { id: 'LE-006', userId: 'USR-102', username: 'jane.smith', sourceIp: '91.219.237.22', location: 'Amsterdam, NL', device: 'Linux-Chrome', status: 'failed', riskScore: 65, timestamp: ago(68.2 * H), anomalies: ['Unknown device'] },
  { id: 'LE-007', userId: 'USR-102', username: 'jane.smith', sourceIp: '91.219.237.22', location: 'Amsterdam, NL', device: 'Linux-Chrome', status: 'failed', riskScore: 65, timestamp: ago(68.1 * H), anomalies: ['Unknown device'] },
  { id: 'LE-008', userId: 'USR-102', username: 'jane.smith', sourceIp: '91.219.237.22', location: 'Amsterdam, NL', device: 'Linux-Chrome', status: 'success', riskScore: 88, timestamp: ago(68 * H), anomalies: ['Success after failures', 'Mailbox rule created'] },
  { id: 'LE-009', userId: 'USR-103', username: 'alice.wong', sourceIp: '10.0.1.52', location: 'Singapore, SG', device: 'MacOS-Chrome', status: 'success', riskScore: 3, timestamp: ago(60 * H), anomalies: [] },
  { id: 'LE-010', userId: 'USR-104', username: 'bob.marley', sourceIp: '10.0.1.61', location: 'London, UK', device: 'Windows-Edge', status: 'success', riskScore: 4, timestamp: ago(56 * H), anomalies: [] },
  { id: 'LE-011', userId: 'USR-105', username: 'emma.davis', sourceIp: '91.219.238.100', location: 'Frankfurt, DE', device: 'Windows-Firefox', status: 'success', riskScore: 55, timestamp: ago(44.2 * H), anomalies: ['Valid password from new IP'] },
  { id: 'LE-012', userId: 'USR-105', username: 'emma.davis', sourceIp: '10.0.1.70', location: 'Austin, US', device: 'Windows-Chrome', status: 'success', riskScore: 3, timestamp: ago(44 * H), anomalies: [] },
  { id: 'LE-013', userId: 'USR-106', username: 'svc-reports', sourceIp: '45.33.22.10', location: 'Fremont, US', device: 'Unknown-CLI', status: 'success', riskScore: 85, timestamp: ago(38 * H), anomalies: ['Off-hours', 'New source IP', 'Service account interactive'] },
  { id: 'LE-014', userId: 'USR-107', username: 'mike.ross', sourceIp: '10.0.2.88', location: 'Chicago, US', device: 'Windows-Chrome', status: 'success', riskScore: 5, timestamp: ago(34 * H), anomalies: [] },
  { id: 'LE-015', userId: 'USR-101', username: 'john.doe', sourceIp: '10.0.1.45', location: 'New York, US', device: 'Windows-Chrome', status: 'success', riskScore: 4, timestamp: ago(30 * H), anomalies: [] },
  { id: 'LE-016', userId: 'USR-108', username: 'laura.perez', sourceIp: '10.0.1.77', location: 'Madrid, ES', device: 'MacOS-Safari', status: 'success', riskScore: 3, timestamp: ago(26 * H), anomalies: [] },
  { id: 'LE-017', userId: 'USR-109', username: 'david.kim', sourceIp: '10.0.3.14', location: 'Seoul, KR', device: 'Windows-Chrome', status: 'success', riskScore: 45, timestamp: ago(24.5 * H), anomalies: ['Off-hours export activity'] },
  { id: 'LE-018', userId: 'USR-110', username: 'admin.root', sourceIp: '10.0.0.9', location: 'New York, US', device: 'Linux-CLI', status: 'success', riskScore: 2, timestamp: ago(24 * H), anomalies: [] },
  { id: 'LE-019', userId: 'USR-111', username: 'hr.bot', sourceIp: '10.0.5.20', location: 'New York, US', device: 'Service-Runner', status: 'success', riskScore: 2, timestamp: ago(20 * H), anomalies: [] },
  { id: 'LE-020', userId: 'USR-112', username: 'tom.hardy', sourceIp: '45.33.31.88', location: 'Fremont, US', device: 'Linux-CLI', status: 'failed', riskScore: 60, timestamp: ago(50.5 * H), anomalies: ['SSH brute force source'] },
  { id: 'LE-021', userId: 'USR-112', username: 'tom.hardy', sourceIp: '10.0.1.90', location: 'Toronto, CA', device: 'Windows-Chrome', status: 'success', riskScore: 3, timestamp: ago(48 * H), anomalies: [] },
  { id: 'LE-022', userId: 'USR-113', username: 'nina.williams', sourceIp: '10.0.1.95', location: 'Berlin, DE', device: 'MacOS-Chrome', status: 'success', riskScore: 4, timestamp: ago(40 * H), anomalies: [] },
  { id: 'LE-023', userId: 'USR-114', username: 'paul.walker', sourceIp: '185.220.101.9', location: 'Moscow, RU', device: 'Linux-CLI', status: 'failed', riskScore: 68, timestamp: ago(12 * H), anomalies: ['Password spraying source'] },
  { id: 'LE-024', userId: 'USR-115', username: 'carol.danvers', sourceIp: '185.220.101.9', location: 'Moscow, RU', device: 'Linux-CLI', status: 'failed', riskScore: 68, timestamp: ago(11.9 * H), anomalies: ['Password spraying source'] },
  { id: 'LE-025', userId: 'USR-116', username: 'steve.rogers', sourceIp: '185.220.101.9', location: 'Moscow, RU', device: 'Linux-CLI', status: 'failed', riskScore: 68, timestamp: ago(11.8 * H), anomalies: ['Password spraying source'] },
  { id: 'LE-026', userId: 'USR-101', username: 'john.doe', sourceIp: '10.0.1.45', location: 'New York, US', device: 'Windows-Chrome', status: 'success', riskScore: 3, timestamp: ago(10 * H), anomalies: [] },
  { id: 'LE-027', userId: 'USR-103', username: 'alice.wong', sourceIp: '10.0.1.52', location: 'Singapore, SG', device: 'MacOS-Chrome', status: 'success', riskScore: 4, timestamp: ago(8 * H), anomalies: [] },
  { id: 'LE-028', userId: 'USR-117', username: 'finance.audit', sourceIp: '10.0.5.31', location: 'New York, US', device: 'Service-Runner', status: 'success', riskScore: 2, timestamp: ago(6 * H), anomalies: [] },
  { id: 'LE-029', userId: 'USR-118', username: 'peter.parker', sourceIp: '10.0.1.101', location: 'Queens, US', device: 'Windows-Firefox', status: 'failed', riskScore: 25, timestamp: ago(3 * H), anomalies: ['Single failed attempt'] },
  { id: 'LE-030', userId: 'USR-118', username: 'peter.parker', sourceIp: '10.0.1.101', location: 'Queens, US', device: 'Windows-Firefox', status: 'success', riskScore: 5, timestamp: ago(2.9 * H), anomalies: [] },
  { id: 'LE-031', userId: 'USR-119', username: 'wanda.maximoff', sourceIp: '10.0.1.110', location: 'Sokovia, EU', device: 'MacOS-Chrome', status: 'success', riskScore: 30, timestamp: ago(1.5 * H), anomalies: ['Off-hours login (02:10 UTC)'] },
  { id: 'LE-032', userId: 'USR-120', username: 'sam.wilson', sourceIp: '10.0.1.120', location: 'Miami, US', device: 'iOS-Safari', status: 'success', riskScore: 3, timestamp: ago(0.8 * H), anomalies: [] },
];

// ---------------------------------------------------------------------------
// NETWORK FLOWS (20+)
// ---------------------------------------------------------------------------
export const mockNetworkFlows: NetworkFlow[] = [
  { id: 'NF-001', sourceIp: '10.0.4.21', destIp: '45.33.32.156', destDomain: 'cdn-updates-secure.top', port: 4444, protocol: 'TCP', bytesOut: 4700000000, bytesIn: 21000000, anomalyScore: 0.97, flags: ['High volume', 'Suspicious port', 'Beaconing'], timestamp: ago(8 * M) },
  { id: 'NF-002', sourceIp: '10.0.7.2', destIp: '185.220.101.45', destDomain: 'tor-exit-4.torproject.org', port: 9001, protocol: 'TCP', bytesOut: 48000000, bytesIn: 52000000, anomalyScore: 0.94, flags: ['Tor exit', 'Beaconing 120s'], timestamp: ago(22 * H) },
  { id: 'NF-003', sourceIp: '10.0.2.88', destIp: '8.8.8.8', destDomain: 'exfil-dns.top', port: 53, protocol: 'UDP', bytesOut: 1240000, bytesIn: 82000, anomalyScore: 0.88, flags: ['DNS tunneling pattern', 'High NXDOMAIN ratio'], timestamp: ago(11 * H) },
  { id: 'NF-004', sourceIp: '10.0.3.14', destIp: '10.0.3.255', destDomain: 'internal-fileshare', port: 445, protocol: 'TCP', bytesOut: 2100000000, bytesIn: 410000000, anomalyScore: 0.72, flags: ['Internal lateral', 'Large transfer'], timestamp: ago(30 * H) },
  { id: 'NF-005', sourceIp: '10.0.1.45', destIp: '13.107.42.14', destDomain: 'outlook.office365.com', port: 443, protocol: 'TLS', bytesOut: 2400000, bytesIn: 18000000, anomalyScore: 0.05, flags: [], timestamp: ago(70 * H) },
  { id: 'NF-006', sourceIp: '10.0.1.50', destIp: '17.253.144.10', destDomain: 'swcdn.apple.com', port: 443, protocol: 'TLS', bytesOut: 12000000, bytesIn: 850000000, anomalyScore: 0.08, flags: [], timestamp: ago(66 * H) },
  { id: 'NF-007', sourceIp: '10.0.1.52', destIp: '104.16.132.229', destDomain: 'www.atlassian.com', port: 443, protocol: 'TLS', bytesOut: 3400000, bytesIn: 15000000, anomalyScore: 0.06, flags: [], timestamp: ago(60 * H) },
  { id: 'NF-008', sourceIp: '10.0.5.20', destIp: '34.107.221.82', destDomain: 'api.internal-hr.local', port: 443, protocol: 'TLS', bytesOut: 900000, bytesIn: 4200000, anomalyScore: 0.04, flags: [], timestamp: ago(20 * H) },
  { id: 'NF-009', sourceIp: '10.0.6.11', destIp: '45.33.19.79', destDomain: 'payload-delivery.top', port: 8080, protocol: 'TCP', bytesOut: 2200000, bytesIn: 41000000, anomalyScore: 0.91, flags: ['Suspicious port', 'Executable download'], timestamp: ago(16 * H) },
  { id: 'NF-010', sourceIp: '10.0.1.90', destIp: '151.101.1.69', destDomain: 'www.reddit.com', port: 443, protocol: 'TLS', bytesOut: 1800000, bytesIn: 22000000, anomalyScore: 0.09, flags: [], timestamp: ago(48 * H) },
  { id: 'NF-011', sourceIp: '10.0.8.4', destIp: '185.220.101.44', destDomain: 'paypa1-secure.top', port: 80, protocol: 'HTTP', bytesOut: 450000, bytesIn: 3100000, anomalyScore: 0.82, flags: ['Lookalike domain', 'Plaintext credentials likely'], timestamp: ago(55 * H) },
  { id: 'NF-012', sourceIp: '10.0.2.30', destIp: '52.94.236.248', destDomain: 's3.amazonaws.com', port: 443, protocol: 'TLS', bytesOut: 41000000, bytesIn: 2100000000, anomalyScore: 0.11, flags: ['Large download (backup job)'], timestamp: ago(36 * H) },
  { id: 'NF-013', sourceIp: '10.0.4.21', destIp: '45.33.32.156', destDomain: 'cdn-updates-secure.top', port: 4444, protocol: 'TCP', bytesOut: 47000000, bytesIn: 2100000, anomalyScore: 0.96, flags: ['Beaconing 60s', 'Suspicious port'], timestamp: ago(38 * M) },
  { id: 'NF-014', sourceIp: '10.0.4.21', destIp: '45.33.32.156', destDomain: 'cdn-updates-secure.top', port: 4444, protocol: 'TCP', bytesOut: 46800000, bytesIn: 2090000, anomalyScore: 0.96, flags: ['Beaconing 60s', 'Suspicious port'], timestamp: ago(98 * M) },
  { id: 'NF-015', sourceIp: '10.0.1.77', destIp: '142.250.185.99', destDomain: 'mail.google.com', port: 443, protocol: 'TLS', bytesOut: 2200000, bytesIn: 16000000, anomalyScore: 0.05, flags: [], timestamp: ago(26 * H) },
  { id: 'NF-016', sourceIp: '10.0.0.9', destIp: '10.0.0.2', destDomain: 'dc01.corp.local', port: 389, protocol: 'TCP', bytesOut: 340000, bytesIn: 1200000, anomalyScore: 0.07, flags: [], timestamp: ago(24 * H) },
  { id: 'NF-017', sourceIp: '10.0.9.5', destIp: '45.33.22.10', destDomain: 'unknown', port: 31337, protocol: 'TCP', bytesOut: 8200000, bytesIn: 340000, anomalyScore: 0.93, flags: ['Suspicious port 31337', 'Unresolved destination'], timestamp: ago(38 * H) },
  { id: 'NF-018', sourceIp: '10.0.1.101', destIp: '140.82.121.4', destDomain: 'github.com', port: 443, protocol: 'TLS', bytesOut: 1600000, bytesIn: 9100000, anomalyScore: 0.04, flags: [], timestamp: ago(3 * H) },
  { id: 'NF-019', sourceIp: '10.0.2.88', destIp: '1.1.1.1', destDomain: 'aGVsbG8ud29ybGQ.exfil-dns.top', port: 53, protocol: 'UDP', bytesOut: 82000, bytesIn: 9400, anomalyScore: 0.89, flags: ['Encoded subdomain', 'DNS tunneling'], timestamp: ago(11.2 * H) },
  { id: 'NF-020', sourceIp: '10.0.1.120', destIp: '20.42.65.92', destDomain: 'teams.microsoft.com', port: 443, protocol: 'TLS', bytesOut: 5400000, bytesIn: 32000000, anomalyScore: 0.06, flags: [], timestamp: ago(48 * M) },
  { id: 'NF-021', sourceIp: '10.0.3.50', destIp: '185.220.101.7', destDomain: 'unknown', port: 6667, protocol: 'TCP', bytesOut: 940000, bytesIn: 220000, anomalyScore: 0.9, flags: ['IRC C2 port', 'Known bad IP'], timestamp: ago(6 * H) },
  { id: 'NF-022', sourceIp: '10.0.1.61', destIp: '13.225.78.90', destDomain: 'd2znquqzjjnbpz.cloudfront.net', port: 443, protocol: 'TLS', bytesOut: 1100000, bytesIn: 12000000, anomalyScore: 0.05, flags: [], timestamp: ago(56 * H) },
];

// ---------------------------------------------------------------------------
// API LOGS (15+)
// ---------------------------------------------------------------------------
export const mockApiLogs: ApiLogEntry[] = [
  { id: 'API-001', endpoint: '/api/v1/login', method: 'POST', sourceIp: '45.33.49.12', userAgent: 'python-requests/2.31.0', statusCode: 401, responseTime: 210, anomalyScore: 0.85, flags: ['Credential stuffing'], timestamp: ago(3 * H) },
  { id: 'API-002', endpoint: '/api/v1/login', method: 'POST', sourceIp: '45.33.49.12', userAgent: 'python-requests/2.31.0', statusCode: 401, responseTime: 198, anomalyScore: 0.85, flags: ['Credential stuffing'], timestamp: ago(3 * H - 1000) },
  { id: 'API-003', endpoint: '/api/v1/login', method: 'POST', sourceIp: '45.33.49.13', userAgent: 'python-requests/2.31.0', statusCode: 401, responseTime: 240, anomalyScore: 0.84, flags: ['Credential stuffing'], timestamp: ago(3 * H - 2000) },
  { id: 'API-004', endpoint: '/api/v1/users/1042', method: 'GET', sourceIp: '10.0.5.40', userAgent: 'cyberguard-sync/1.2', statusCode: 200, responseTime: 45, anomalyScore: 0.62, flags: ['Bulk sequential access'], timestamp: ago(20 * H) },
  { id: 'API-005', endpoint: '/api/v1/users/1043', method: 'GET', sourceIp: '10.0.5.40', userAgent: 'cyberguard-sync/1.2', statusCode: 200, responseTime: 44, anomalyScore: 0.62, flags: ['Bulk sequential access'], timestamp: ago(20 * H - 1200) },
  { id: 'API-006', endpoint: '/api/v1/users/1044', method: 'GET', sourceIp: '10.0.5.40', userAgent: 'cyberguard-sync/1.2', statusCode: 200, responseTime: 46, anomalyScore: 0.61, flags: ['Bulk sequential access'], timestamp: ago(20 * H - 2500) },
  { id: 'API-007', endpoint: '/api/v1/orders', method: 'GET', sourceIp: '10.0.6.2', userAgent: 'Mozilla/5.0 (Macintosh)', statusCode: 200, responseTime: 88, anomalyScore: 0.04, flags: [], timestamp: ago(5 * H) },
  { id: 'API-008', endpoint: '/api/v1/products', method: 'GET', sourceIp: '10.0.6.15', userAgent: 'Mozilla/5.0 (Windows NT 10.0)', statusCode: 200, responseTime: 61, anomalyScore: 0.03, flags: [], timestamp: ago(5.2 * H) },
  { id: 'API-009', endpoint: '/api/v1/admin/debug', method: 'GET', sourceIp: '45.33.50.99', userAgent: 'curl/8.4.0', statusCode: 404, responseTime: 12, anomalyScore: 0.88, flags: ['Admin probing'], timestamp: ago(9 * H) },
  { id: 'API-010', endpoint: '/.env', method: 'GET', sourceIp: '45.33.50.99', userAgent: 'curl/8.4.0', statusCode: 404, responseTime: 8, anomalyScore: 0.92, flags: ['Secrets probing'], timestamp: ago(9 * H - 500) },
  { id: 'API-011', endpoint: '/wp-admin/setup.php', method: 'GET', sourceIp: '45.33.50.99', userAgent: 'curl/8.4.0', statusCode: 404, responseTime: 9, anomalyScore: 0.9, flags: ['Admin probing'], timestamp: ago(9 * H - 900) },
  { id: 'API-012', endpoint: '/api/v1/data-lake/restricted/objects', method: 'GET', sourceIp: '10.0.5.55', userAgent: 'aws-sdk-java/2.20', statusCode: 200, responseTime: 320, anomalyScore: 0.7, flags: ['First access to restricted prefix', 'Bulk download'], timestamp: ago(72 * H) },
  { id: 'API-013', endpoint: '/api/v1/reports/weekly', method: 'GET', sourceIp: '10.0.5.55', userAgent: 'aws-sdk-java/2.20', statusCode: 200, responseTime: 180, anomalyScore: 0.1, flags: [], timestamp: ago(70 * H) },
  { id: 'API-014', endpoint: '/api/v1/login', method: 'POST', sourceIp: '91.219.239.5', userAgent: 'Go-http-client/2.0', statusCode: 401, responseTime: 205, anomalyScore: 0.8, flags: ['Auth failure'], timestamp: ago(1.5 * H) },
  { id: 'API-015', endpoint: '/api/v1/login', method: 'POST', sourceIp: '91.219.239.5', userAgent: 'Go-http-client/2.0', statusCode: 401, responseTime: 199, anomalyScore: 0.8, flags: ['Auth failure'], timestamp: ago(1.5 * H - 800) },
  { id: 'API-016', endpoint: '/api/v1/login', method: 'POST', sourceIp: '91.219.239.5', userAgent: 'Go-http-client/2.0', statusCode: 401, responseTime: 220, anomalyScore: 0.8, flags: ['Auth failure'], timestamp: ago(1.5 * H - 1600) },
  { id: 'API-017', endpoint: '/api/v1/health', method: 'GET', sourceIp: '10.0.0.1', userAgent: 'kubernetes-probe/1.0', statusCode: 200, responseTime: 3, anomalyScore: 0.01, flags: [], timestamp: ago(0.2 * H) },
  { id: 'API-018', endpoint: '/api/v1/customers/export', method: 'GET', sourceIp: '10.0.3.14', userAgent: 'Mozilla/5.0 (Windows NT 10.0)', statusCode: 200, responseTime: 4200, anomalyScore: 0.68, flags: ['Bulk export', 'Pre-departure window'], timestamp: ago(30 * H) },
];

// ---------------------------------------------------------------------------
// AUDIT LOGS (30+)
// ---------------------------------------------------------------------------
export const mockAuditLogs: AuditLog[] = [
  { id: 'AUD-001', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'LOGIN', resource: 'auth/session', details: 'Successful login from 10.0.0.5', timestamp: ago(12 * M) },
  { id: 'AUD-002', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'VIEW_ALERT', resource: 'ALT-001', details: 'Viewed alert detail: Microsoft Credential Harvesting', timestamp: ago(11 * M) },
  { id: 'AUD-003', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'EXECUTE_ACTION', resource: 'RA-001', details: 'Executed Quarantine Email (simulated) for ALT-001', timestamp: ago(10 * M) },
  { id: 'AUD-004', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'CREATE_INCIDENT', resource: 'INC-001', details: 'Created incident from alert ALT-001', timestamp: ago(14 * M) },
  { id: 'AUD-005', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'UPDATE_INCIDENT', resource: 'INC-001', details: 'Status changed open -> investigating', timestamp: ago(10 * M) },
  { id: 'AUD-006', userId: 'USR-003', userName: 'bob.kumar@company.com', action: 'CREATE_INCIDENT', resource: 'INC-002', details: 'Created incident from alert ALT-002', timestamp: ago(30 * M) },
  { id: 'AUD-007', userId: 'USR-003', userName: 'bob.kumar@company.com', action: 'VIEW_ALERT', resource: 'ALT-002', details: 'Viewed alert detail: Impossible Travel Login', timestamp: ago(31 * M) },
  { id: 'AUD-008', userId: 'USR-004', userName: 'carlos.reyes@company.com', action: 'APPROVE_ACTION', resource: 'RA-021', details: 'Approved semi-automatic action: Isolate Host 10.0.4.21', timestamp: ago(6 * H) },
  { id: 'AUD-009', userId: 'SYSTEM', userName: 'system', action: 'EXECUTE_ACTION', resource: 'RA-021', details: 'Executed Isolate Host (simulated) on 10.0.4.21', timestamp: ago(6 * H - 2000) },
  { id: 'AUD-010', userId: 'USR-004', userName: 'carlos.reyes@company.com', action: 'UPDATE_INCIDENT', resource: 'INC-003', details: 'Status changed investigating -> contained', timestamp: ago(5 * H) },
  { id: 'AUD-011', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'ANALYZE_EMAIL', resource: 'analysis', details: 'Ran phishing analysis on sample email', timestamp: ago(4.5 * H) },
  { id: 'AUD-012', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'ANALYZE_URL', resource: 'analysis', details: 'Ran URL analysis on paypa1-secure.top', timestamp: ago(4.2 * H) },
  { id: 'AUD-013', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'ANALYZE_MESSAGE', resource: 'analysis', details: 'Ran impersonation analysis on BEC sample', timestamp: ago(4 * H) },
  { id: 'AUD-014', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'UPDATE_ALERT', resource: 'ALT-004', details: 'Alert status changed new -> acknowledged', timestamp: ago(2 * H) },
  { id: 'AUD-015', userId: 'USR-003', userName: 'bob.kumar@company.com', action: 'VIEW_REPORT', resource: 'reports', details: 'Generated JSON report export', timestamp: ago(1.8 * H) },
  { id: 'AUD-016', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'EXPORT_REPORT', resource: 'reports/json', details: 'Downloaded JSON threat report', timestamp: ago(1.7 * H) },
  { id: 'AUD-017', userId: 'USR-004', userName: 'carlos.reyes@company.com', action: 'EXPORT_REPORT', resource: 'reports/csv', details: 'Downloaded CSV alerts export', timestamp: ago(1.5 * H) },
  { id: 'AUD-018', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'UPDATE_ALERT', resource: 'ALT-010', details: 'Alert status changed new -> resolved', timestamp: ago(9 * H) },
  { id: 'AUD-019', userId: 'USR-003', userName: 'bob.kumar@company.com', action: 'UPDATE_ALERT', resource: 'ALT-015', details: 'Alert status changed new -> dismissed', timestamp: ago(18 * H) },
  { id: 'AUD-020', userId: 'USR-004', userName: 'carlos.reyes@company.com', action: 'CREATE_INCIDENT', resource: 'INC-007', details: 'Created insider threat incident from ALT-018', timestamp: ago(28 * H) },
  { id: 'AUD-021', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'APPROVE_ACTION', resource: 'RA-171', details: 'Approved revoke export rights for david.kim', timestamp: ago(25 * H) },
  { id: 'AUD-022', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'LOGIN_FAILED', resource: 'auth/session', details: 'Failed login attempt with invalid password from 10.0.0.99', timestamp: ago(24 * H) },
  { id: 'AUD-023', userId: 'USR-003', userName: 'bob.kumar@company.com', action: 'ASSIGN_INCIDENT', resource: 'INC-005', details: 'Assigned incident INC-005 to Bob Kumar', timestamp: ago(53 * H) },
  { id: 'AUD-024', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'CLOSE_INCIDENT', resource: 'INC-004', details: 'Status changed contained -> closed', timestamp: ago(40 * H) },
  { id: 'AUD-025', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'SETTINGS_VIEW', resource: 'settings', details: 'Viewed settings page', timestamp: ago(36 * H) },
  { id: 'AUD-026', userId: 'SYSTEM', userName: 'system', action: 'SIMULATION_ALERT', resource: 'alerts', details: 'Live simulation generated synthetic alert for demo purposes', timestamp: ago(30 * H) },
  { id: 'AUD-027', userId: 'USR-004', userName: 'carlos.reyes@company.com', action: 'APPROVE_ACTION', resource: 'RA-241', details: 'Approved session revocation for jane.smith', timestamp: ago(65 * H) },
  { id: 'AUD-028', userId: 'SYSTEM', userName: 'system', action: 'EXECUTE_ACTION', resource: 'RA-243', details: 'Removed malicious forwarding rule for jane.smith (simulated)', timestamp: ago(64 * H) },
  { id: 'AUD-029', userId: 'USR-002', userName: 'alice.chen@company.com', action: 'UPDATE_INCIDENT', resource: 'INC-008', details: 'Status changed investigating -> contained', timestamp: ago(60 * H) },
  { id: 'AUD-030', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'CHAT_ASSISTANT', resource: 'soc-assistant', details: 'Queried SOC assistant: summarize today threats', timestamp: ago(2 * H) },
  { id: 'AUD-031', userId: 'USR-003', userName: 'bob.kumar@company.com', action: 'VIEW_AUDIT', resource: 'audit-logs', details: 'Viewed audit log page', timestamp: ago(1 * H) },
  { id: 'AUD-032', userId: 'USR-001', userName: 'admin@cyberguard.local', action: 'LOGOUT', resource: 'auth/session', details: 'User logged out', timestamp: ago(50 * M) },
];

// ---------------------------------------------------------------------------
// RESPONSE ACTION CATALOG (12)
// ---------------------------------------------------------------------------
export const mockResponseCatalog: ResponseActionCatalog[] = [
  { id: 'RA-C01', action: 'Quarantine Email', targetType: 'email_message', automationLevel: 'automatic', requiresApproval: false, description: 'Remove a phishing email from all recipient inboxes via mail gateway' },
  { id: 'RA-C02', action: 'Block Sender Domain', targetType: 'domain', automationLevel: 'automatic', requiresApproval: false, description: 'Add a sender domain to the mail gateway blocklist' },
  { id: 'RA-C03', action: 'Block Destination IP', targetType: 'ip_address', automationLevel: 'semi-automatic', requiresApproval: true, description: 'Blackhole an IP at the perimeter firewall; requires analyst approval' },
  { id: 'RA-C04', action: 'Block URL', targetType: 'url', automationLevel: 'automatic', requiresApproval: false, description: 'Add a URL/domain to the web-filter deny list' },
  { id: 'RA-C05', action: 'Revoke Active Sessions', targetType: 'user_account', automationLevel: 'semi-automatic', requiresApproval: true, description: 'Terminate all active sessions for a user account' },
  { id: 'RA-C06', action: 'Force Password Reset', targetType: 'user_account', automationLevel: 'automatic', requiresApproval: false, description: 'Require password change and MFA re-enrollment at next login' },
  { id: 'RA-C07', action: 'Isolate Host', targetType: 'host', automationLevel: 'semi-automatic', requiresApproval: true, description: 'Quarantine an endpoint from the network pending investigation' },
  { id: 'RA-C08', action: 'Apply Rate Limit', targetType: 'ip_address', automationLevel: 'automatic', requiresApproval: false, description: 'Throttle an abusive client at the API gateway/WAF' },
  { id: 'RA-C09', action: 'Revoke API Token', targetType: 'api_token', automationLevel: 'semi-automatic', requiresApproval: true, description: 'Invalidate an API credential suspected of abuse' },
  { id: 'RA-C10', action: 'Flag for Manual Verification', targetType: 'media_file', automationLevel: 'manual', requiresApproval: false, description: 'Route media to human analysts for deepfake review' },
  { id: 'RA-C11', action: 'Notify Targeted Users', targetType: 'user_group', automationLevel: 'manual', requiresApproval: false, description: 'Send security awareness communication to affected users' },
  { id: 'RA-C12', action: 'Freeze Pending Financial Requests', targetType: 'payment', automationLevel: 'semi-automatic', requiresApproval: true, description: 'Hold wire transfers or purchases pending fraud verification' },
];

// ---------------------------------------------------------------------------
// RESPONSE EXECUTION HISTORY (6+)
// ---------------------------------------------------------------------------
export const mockResponseHistory: ResponseExecution[] = [
  { id: 'EXE-001', actionId: 'RA-C01', actionName: 'Quarantine Email', target: 'ALT-001 (34 inboxes)', status: 'executed', executedBy: 'system (automatic)', timestamp: ago(9 * M) },
  { id: 'EXE-002', actionId: 'RA-C07', actionName: 'Isolate Host', target: '10.0.4.21', status: 'executed', executedBy: 'carlos.reyes@company.com', approvedBy: 'carlos.reyes@company.com', timestamp: ago(6 * H) },
  { id: 'EXE-003', actionId: 'RA-C06', actionName: 'Force Password Reset', target: 'alice.wong@company.com', status: 'executed', executedBy: 'system (automatic)', timestamp: ago(53 * H) },
  { id: 'EXE-004', actionId: 'RA-C05', actionName: 'Revoke Active Sessions', target: 'jane.smith@company.com', status: 'executed', executedBy: 'alice.chen@company.com', approvedBy: 'carlos.reyes@company.com', timestamp: ago(65 * H) },
  { id: 'EXE-005', actionId: 'RA-C03', actionName: 'Block Destination IP', target: '45.33.32.156', status: 'executed', executedBy: 'carlos.reyes@company.com', approvedBy: 'carlos.reyes@company.com', timestamp: ago(6.2 * H) },
  { id: 'EXE-006', actionId: 'RA-C08', actionName: 'Apply Rate Limit', target: '45.33.49.12', status: 'executed', executedBy: 'system (automatic)', timestamp: ago(2.9 * H) },
  { id: 'EXE-007', actionId: 'RA-C12', actionName: 'Freeze Pending Financial Requests', target: 'Wire #WF-88213 ($250,000)', status: 'approved', executedBy: 'bob.kumar@company.com', approvedBy: 'cfo-office@company.com', timestamp: ago(3.5 * H) },
  { id: 'EXE-008', actionId: 'RA-C09', actionName: 'Revoke API Token', target: 'svc-reports-token', status: 'pending', executedBy: 'bob.kumar@company.com', timestamp: ago(20 * M) },
];

// ---------------------------------------------------------------------------
// Mutable store used by mockApi (clone-on-read to avoid accidental mutation)
// ---------------------------------------------------------------------------
export const db = {
  alerts: [...mockAlerts],
  incidents: [...mockIncidents],
  loginEvents: [...mockLoginEvents],
  networkFlows: [...mockNetworkFlows],
  apiLogs: [...mockApiLogs],
  auditLogs: [...mockAuditLogs],
  responseCatalog: [...mockResponseCatalog],
  responseHistory: [...mockResponseHistory],
};

export function addAuditLog(entry: Omit<AuditLog, 'id' | 'timestamp'>): void {
  db.auditLogs.unshift({
    ...entry,
    id: `AUD-${db.auditLogs.length + 1}`,
    timestamp: new Date().toISOString(),
  });
}
